# Generated by Django 5.1.3 on 2026-04-02 16:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_daehwa', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/foto_usuario/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('L', 'Logopeda'), ('F', 'Familiar')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_permissions', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('foto_paciente', models.ImageField(blank=True, null=True, upload_to='imagenes/foto_paciente/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('familiar', models.ForeignKey(limit_choices_to={'rol': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='familiar_registrado', to=settings.AUTH_USER_MODEL)),
                ('logopeda_asignado', models.ForeignKey(limit_choices_to={'rol': 'L'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion_Inicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes_clinicos', models.TextField(blank=True, null=True)),
                ('entorno_familiar', models.TextField(blank=True, null=True)),
                ('pruebas', models.TextField(blank=True, null=True)),
                ('archivos_adjuntos', models.FileField(blank=True, null=True, upload_to='archivos/evaluacion_inicial/')),
                ('observacion_directa', models.TextField(blank=True, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_inicial', to='app_daehwa.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico_Funcional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('diagnostico_funcional', models.TextField()),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico_funcional', to='app_daehwa.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('id_usuario_logopeda', models.ForeignKey(limit_choices_to={'rol': 'Logopeda'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='app_daehwa.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivos_especificos', models.TextField()),
                ('contenidos', models.TextField()),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion_sesiones', models.CharField(max_length=100)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_intervencion', to='app_daehwa.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Sesiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('actividades', models.TextField()),
                ('areas_lenguaje', models.CharField(max_length=225)),
                ('logros', models.TextField(blank=True, null=True)),
                ('aspectos_mejorar', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('multimedia', models.FileField(blank=True, null=True, upload_to='archivos/registro_sesiones/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='app_daehwa.paciente')),
            ],
        ),
    ]
