# Generated by Django 5.1.3 on 2026-05-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_daehwa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico_funcional',
            name='diagnostico_funcional',
            field=models.TextField(blank=True),
        ),
    ]
