# Generated by Django 5.1.3 on 2026-04-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_daehwa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='test', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
