# Generated by Django 5.1.3 on 2026-04-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_daehwa', '0002_usuario_foto_usuario_alter_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='diagnostico_funcional',
            options={'verbose_name': 'Diagnóstico_Funcional'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion_inicial',
            options={'verbose_name': 'Evaluacion_Inicial'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='plan_intervencion',
            options={'verbose_name': 'Plan_Intervencion'},
        ),
        migrations.AlterModelOptions(
            name='registro_sesiones',
            options={'verbose_name': 'Registro_Sesion', 'verbose_name_plural': 'Registro_Sesiones'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
