# Generated by Django 5.1.3 on 2026-05-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_daehwa', '0002_alter_diagnostico_funcional_diagnostico_funcional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico_funcional',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
