# Generated by Django 5.1.3 on 2026-05-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_daehwa', '0003_alter_diagnostico_funcional_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico_funcional',
            name='fecha',
            field=models.DateField(),
        ),
    ]
